version: '3'

services:
  mariadb:
    image: mariadb
    environment:
      MARIADB_DATABASE: keycloak
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes' # aposztrófok nélkül boolean true-ként értelmezi
      MARIADB_USER: keycloak
      MARIADB_PASSWORD: keycloak
    expose:
      - 3306
    ports:
      - 3306:3306

  keycloak:
    image: jboss/keycloak:16.1.1
    depends_on:
      - mariadb
    environment:
      KEYCLOAK_FRONTEND_URL: http://keycloak.training:8080/auth/
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: root
      DB_VENDOR: mariadb
      DB_ADDR: mariadb # domain name
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    expose:
      - 8080
    ports:
      - 8080:8080

  employees-ui:
    image: training360/keycloak-employees-ui:0.0.1
    depends_on:
      - employees
    environment:
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
      EMPLOYEES-UI_FRONTEND-URL: http://employees-ui.training:8081
      EMPLOYEES-UI_AUTH-SERVER-FRONTEND-URL: http://keycloak.training:8080/auth
      EMPLOYEES-UI_EMPLOYEES-URL: http://employees:8080/api/employees
    expose:
      - 8080
    ports:
      - 8081:8080

  employees:
    image: training360/keycloak-employees:0.0.1
    environment:
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth
    expose:
      - 8080
    ports:
      - 8082:8080

  mailhog:
    image: mailhog/mailhog:v1.0.1
    expose:
      - 1025
      - 8025
    ports:
      - 1025:1025
      - 8025:8025
  
  openldap:
    image: bitnami/openldap:2.6.1
    environment:
      BITNAMI_DEBUG: "true"
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: admin
      LDAP_USERS: johnldap,jackldap,janeldap
      LDAP_PASSWORDS: johnldap,jackldap,janeldap
    expose:
      - 1389
    ports:
      - 8389:1389